server:
  port: 9011
spring:
  application:
    name: tensquare-manager

jwt:
  config:
    key: itcast


eureka:
  client:
    serviceUrl:  #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare-base:
      path: /base/**
      serverceId: tensquare-base
    tensquare-user:
      path: /user/**
      serverceId: tensquare-user
    tensquare-qa:
      path: /qa/**
      serverceId: tensquare-qa
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000