server:
  port: 12000
spring:
  application:
    name: tensquare‐config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/araneae/tensquare_dev.git
  rabbitmq:
    host: 192.168.254.129
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
